config/routes.rb
Rails.application.routes.draw do

  root 'stores#index'
  resources :stores 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :store
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  before_create :put_item_in_stock

  private 

  def put_item_in_stock
    self.in_stock = true 
  end 

  def self.items_in_stock
    where(in_stock: true)
  end 

end

app/models/list.rb
class List < ApplicationRecord

  belongs_to :store
  has_many :items, dependent: :destroy

end

app/models/store.rb
class Store < ApplicationRecord
  # relations
  has_one :address
  has_many :lists
  before_destroy :delete_associations

  # validations
  validates :name, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
  validates_format_of :phone, with: /\A\(?\d{3}\)?[- ]?\d{3}[- ]?\d{4}\z/, on: :create

  #Cool ENUM stuff
  enum state: { active: 0, inactive: 1}

  #Methods
  def self.find_store_name(name)
    where(name: name)
  end

  # Instance/ Class Methods
  def remove_items
    self.lists.joins(:items).destory_all
  end

  # Shhh is private
  private

  def delete_associations
    self.lists.joins(:items).destroy_all if self.lists.joins(:items).present?
    self.lists.destroy_all if self.lists.present?
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  def index
    @stores = Store.all
  end

  def new
    @store = Store.new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private 

    def set_store
      @store = Store.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stores/create.html.erb
<h1>Stores#create</h1>
<p>Find me in app/views/stores/create.html.erb</p>

app/views/stores/destroy.html.erb
<h1>Stores#destroy</h1>
<p>Find me in app/views/stores/destroy.html.erb</p>

app/views/stores/edit.html.erb
<h1>Stores#edit</h1>
<p>Find me in app/views/stores/edit.html.erb</p>

app/views/stores/index.html.erb
Check out these cool store yo!

<%=link_to "Create a New Store", new_store_path%>


This is called echoing 
<ul>
  <% @stores.each do |store|%>
    <li><%=link_to store.name, store_path(store)%></li>
  <%end%>
</ul>

app/views/stores/new.html.erb
<h1>Stores#new</h1>
<p>Find me in app/views/stores/new.html.erb</p>

app/views/stores/show.html.erb
<h3>Welcome to the best store ever!</h3>

<%=@store.name %>

app/views/stores/update.html.erb
<h1>Stores#update</h1>
<p>Find me in app/views/stores/update.html.erb</p>